CREATE TABLE IF NOT EXISTS modems (
  id INT(20) NOT NULL,
  first VARCHAR(30) NOT NULL,
  last VARCHAR(30) NOT NULL,
  account VARCHAR(30) NOT NULL,
  stNum VARCHAR(8) DEFAULT NULL,
  street VARCHAR(30) NOT NULL,
  unit VARCHAR(30) NOT NULL,
  city VARCHAR(40) NOT NULL,
  state VARCHAR(2) NOT NULL,
  zip VARCHAR(9) NOT NULL,
  phone VARCHAR(10) NOT NULL,
  phone2 VARCHAR(10) NOT NULL,
  node VARCHAR(40) NOT NULL,
  sg INT(9) NOT NULL DEFAULT 1,
  profile VARCHAR(48) NOT NULL DEFAULT 'Disabled',
  status INT(3) NOT NULL,
  mac VARCHAR(17) NOT NULL,
  lease_active TINYINT(1) DEFAULT NULL,
  lease_ip VARCHAR(45) DEFAULT NULL,
  lease_error VARCHAR(255) DEFAULT NULL,
  lease_checked_at DATETIME DEFAULT NULL,
  mtamac VARCHAR(17) DEFAULT NULL,
  mtafile VARCHAR(128) DEFAULT NULL,
  username1 VARCHAR(25) DEFAULT NULL,
  displayname1 VARCHAR(25) DEFAULT NULL,
  login1 VARCHAR(25) DEFAULT NULL,
  pass1 VARCHAR(25) DEFAULT NULL,
  username2 VARCHAR(25) DEFAULT NULL,
  displayname2 VARCHAR(25) DEFAULT NULL,
  login2 VARCHAR(25) DEFAULT NULL,
  pass2 VARCHAR(25) DEFAULT NULL,
  oldprofile VARCHAR(48) DEFAULT NULL,
  notes TEXT NOT NULL,
  vdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_modems_mac (mac),
  KEY idx_modems_sg_unit (sg, unit),
  KEY idx_modems_unit (unit)
);

CREATE TABLE IF NOT EXISTS guests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  guest_name VARCHAR(120) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  unit VARCHAR(30) NOT NULL,
  sg INT(9) NOT NULL,
  modem_mac VARCHAR(17) NOT NULL,
  arrival_date DATE NOT NULL,
  departure_date DATE NOT NULL,
  profile_applied VARCHAR(48) NOT NULL,
  dhcp_ip VARCHAR(45) DEFAULT NULL,
  submission_status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  notes TEXT NULL,
  guest_access_id VARCHAR(32) DEFAULT NULL,
  guest_access_code_hash VARCHAR(255) DEFAULT NULL,
  guest_access_code_lookup CHAR(64) DEFAULT NULL,
  guest_access_code_expires_at DATETIME DEFAULT NULL,
  guest_access_failed_attempts INT NOT NULL DEFAULT 0,
  guest_access_locked_until DATETIME DEFAULT NULL,
  guest_access_last_attempt_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY idx_guests_guest_access_id (guest_access_id),
  UNIQUE KEY idx_guests_guest_access_code_lookup (guest_access_code_lookup),
  KEY idx_guests_unit_created (unit, created_at),
  KEY idx_guests_dates (arrival_date, departure_date)
);

CREATE TABLE IF NOT EXISTS guest_self_service_requests (
  id INT NOT NULL AUTO_INCREMENT,
  guest_id INT NOT NULL,
  guest_name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NOT NULL,
  sg INT NOT NULL,
  request_type ENUM('early_checkout', 'extend_departure') NOT NULL,
  current_departure_date DATE NOT NULL,
  requested_departure_date DATE NOT NULL,
  reason TEXT NULL,
  status ENUM('pending', 'approved', 'denied', 'auto_approved') NOT NULL DEFAULT 'pending',
  decision_note TEXT NULL,
  requested_by_access_id VARCHAR(32) NOT NULL,
  decided_by VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_guest_self_service_requests_status_created (status, created_at),
  KEY idx_guest_self_service_requests_guest_id (guest_id)
);

CREATE TABLE IF NOT EXISTS guest_self_service_access_events (
  id INT NOT NULL AUTO_INCREMENT,
  guest_access_id VARCHAR(32) NOT NULL,
  ip_address VARCHAR(64) NOT NULL,
  event_type ENUM('login_success', 'login_failure', 'lockout', 'unlock') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_guest_access_events_access_time (guest_access_id, created_at),
  KEY idx_guest_access_events_ip_time (ip_address, created_at),
  KEY idx_guest_access_events_type_time (event_type, created_at)
);

CREATE TABLE IF NOT EXISTS profile_bootfile_cache (
  sg INT NOT NULL,
  profile_name VARCHAR(128) NOT NULL,
  bootfile_filename VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (sg, profile_name),
  KEY idx_profile_bootfile_cache_sg (sg)
);
